const locations = [
  "Birmingham, AL",
  "Anchorage, AK",
  "Phoenix, AZ",
  "Davis, CA",
  "Los Angeles, CA",
  "Sacramento, CA",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Denver, CO",
  "New Haven, CT",
  "Washington, DC",
  "Pensacola, FL",
  "Tampa Bay, FL",
  "Atlanta, GA",
  "Boise, ID",
  "Chicago, IL",
  "Champaign-Urbana, IL",
  "Indianapolis, IN",
  "Lexington, KY",
  "Louisville, KY",
  "Baltimore, MD",
  "Boston, MA",
  "Detroit, MI",
  "Minneapolis, MN",
  "Kansas City, MO",
  "Springfield, MO",
  "St. Louis, MO",
  "Manchester, NH",
  "Albuquerque, NM",
  "Las Cruces, NM",
  "Albany, NY",
  "Finger Lakes, NY",
  "Long Island, NY",
  "New York City, NY",
  "Syracuse, NY",
  "Columbus, OH",
  "Cleveland, OH",
  "Dayton, OH",
  "Cincinnati, OH",
  "Eugene, OR",
  "Portland, OR",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Lancaster, PA",
  "Chester County, PA",
  "Providence, RI",
  "Columbia, SC",
  "Nashville, TN",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "San Antonio, TX",
  "Salt Lake City, UT",
  "Seattle, WA",
  "Tacoma, WA",
  "Yakima, WA",
  "Milwaukee, WI",
];

module.exports = {
  locations,
};
