const locations = [
  "Oakland, CA",
  "San Francisco, CA",
  "Bellingham, WA",
  "Boston, MA",
  "Chico, CA",
  "Los Angeles, CA",
  "Madison, WI",
  "Newark, NJ",
  "New York City, NY",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "St. Louis, MO",
  "Minneapolis, MN",
  "St. Paul, MN",
  "New Brunswick, NJ",
  "Chicago, IL",
  "Louisville, KY",
  "Houston, TX",
  "Atlanta, GA",
  "Raleigh, NC",
  "Milwaukee, WI",
  "Denver, CO",
  "Mesa, AZ",
  "Fredericksburg, VA",
  "New Bedford, MA",
  "Providence, RI",
  "Cambridge, MA",
  "Seattle, WA",
  "Dallas, TX",
  "Flint, MI",
  "Fort Worth, TX",
  "New Haven, CT",
  "Columbus, OH",
  "Irvine, CA",
  "Holyoke, MA",
  "Greensboro, NC",
  "Cleveland, OH",
  "San Diego, CA",
  "Des Moines, IA",
  "Charlotte, NC",
  "Austin, TX",
  "Portland, ME",
  "Parker, SD",
  "Tulsa, OK",
  "Yellow Springs, OH",
  "Ames, IA",
];

module.exports = {
  locations,
};
